global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: statsd-exporter
    static_configs:
      - targets: ['statsd-exporter:9102']

