name: CI
on:
  push: { branches: [ "main" ] }
  pull_request: {}
jobs:
  lint:
    runs-on: ubuntu-latest
    permissions: { contents: read }  
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: |
          python -m pip install --upgrade pip
          pip install pre-commit flake8
      - run: pre-commit run --all-files
      - run: flake8 .
