name: dbt checks

on:
  pull_request:
    branches: [ main ]

jobs:
  dbt-parse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dbt + adapter (duckdb)
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core==1.9.2 dbt-duckdb==1.9.0

      - name: Ensure dbt profiles.yml
        run: |
          mkdir -p dbt/profiles
          if [ ! -f dbt/profiles/profiles.yml ]; then
            cat > dbt/profiles/profiles.yml <<'PXY'
pt_data_lab:
  config:
    send_anonymous_usage_stats: false
  outputs:
    ci:
      type: duckdb
      path: /tmp/ci.duckdb
      schema: main
  target: ci
PXY
          fi

      - name: dbt deps
        env:
          DBT_PROFILES_DIR: ${{ github.workspace }}/dbt/profiles
        run: dbt deps --profiles-dir "$DBT_PROFILES_DIR"

      - name: dbt parse
        env:
          DBT_PROFILES_DIR: ${{ github.workspace }}/dbt/profiles
        run: dbt parse --profiles-dir "$DBT_PROFILES_DIR"
