name: dbt checks

on:
  pull_request:
    paths:
      - 'dbt/**'
      - 'dbt_project.yml'
      - '.github/workflows/dbt-checks.yml'

jobs:
  dbt-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dbt (core + athena adapter)
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core==1.9.2 dbt-athena-community==1.9.4

      # Perfis dummy para o parse funcionar mesmo sem warehouse
      - name: Ensure dummy profiles.yml (default & ci)
        run: |
          mkdir -p dbt/profiles
          cat > dbt/profiles/profiles.yml <<'YAML'
          default:
            outputs:
              dev:
                type: athena
                s3_staging_dir: s3://dummy
                region_name: us-east-2
                database: dummy
                schema: dummy
                work_group: primary
            target: dev

          ci:
            outputs:
              default:
                type: athena
                s3_staging_dir: s3://dummy
                region_name: us-east-2
                database: dummy
                schema: dummy
                work_group: primary
            target: default
          YAML

      - name: dbt deps & parse (no warehouse)
        env:
          DBT_PROFILES_DIR: ./dbt/profiles
          S3_BUCKET: dummy
          GLUE_DATABASE: dummy
          ATHENA_WORKGROUP: primary
          ATHENA_STAGING_S3: s3://dummy
          AWS_REGION: us-east-2
        run: |
          dbt --version
          if [ -f dbt/dbt_project.yml ]; then
            echo "dbt project found → running deps/parse"
            dbt deps --project-dir dbt
            dbt parse --project-dir dbt
          else
            echo "No dbt/dbt_project.yml found → skipping dbt checks"
          fi
