name: dbt checks

on:
  pull_request:
  workflow_dispatch:

jobs:
  dbt-compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dbt (athena)
        run: |
          python -m pip install --upgrade pip
          pip install "dbt-core==1.9.2" "dbt-athena-community==1.9.4"

      # Usa dbt/profiles do repo; se não existir, cria um profiles.yml mínimo só para o CI
      - name: Choose profiles dir
        id: profiles
        shell: bash
        run: |
          if [ -f dbt/profiles/profiles.yml ]; then
            echo "dir=dbt/profiles" >> "$GITHUB_OUTPUT"
          else
            mkdir -p .github/dbt
            cat > .github/dbt/profiles.yml <<'PROFILES'
default:
  outputs:
    ci:
      type: duckdb
      path: /tmp/ci.duckdb
  target: ci
PROFILES
            echo "dir=.github/dbt" >> "$GITHUB_OUTPUT"
          fi

      - name: dbt deps
        run: dbt deps --project-dir dbt

      - name: dbt parse
        run: dbt parse --project-dir dbt --profiles-dir "${{ steps.profiles.outputs.dir }}"
