name: dbt checks

on:
  pull_request:
  push:
    branches: [ "main" ]
    paths:
      - "dbt/**"
      - ".github/workflows/dbt-checks.yml"

jobs:
  dbt-compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('requirements.txt') }}

      - name: Install dbt (core only)
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core==1.9.2

      - name: dbt sanity
        working-directory: ./dbt
        run: |
          dbt deps
          dbt parse --warn-error
          dbt compile --warn-error
